### ISSUE TITLE
Let's move DOM manipulation out of the Game class 

### ISSUE THREAD

**Issue by probil** [liubich/memory-game#15]
Currently logic inside `Game` class is responsible for different concerns. 
We need to separate them. One of such concerns is DOM manipulation.

Currently it's hard to unit-test `Game` class because it is tightly coupled with DOM. 
Game class should not care about how things is rendered and which path to the image is correct. 

So no `addEventListener` or `target.src = './some_file.svg'` or other DOM stuff in `Game` class.

**Clues**: use separate functions or separate class

**Comment by liubich** [comment]
@probil, is it permissible to use global variables in code?

**Comment by probil** [comment]
Yes, you can create objects or classes or function is the same scope where `Game` class is.
