### ISSUE TITLE
Let's make level selection

### ISSUE THREAD

**Issue by probil** [liubich/memory-game#19]
Let's make game more interesting by adding levels (game complexity):

We need to ask user for game complexity before starting the game. 
By complexity I mean game field size.
- Easy (3x4)
- Medium (4x5)
- Hard (5x7)

So we need separate screen with `select` (with a list of available complexities) and `button` ("Start"). 
Button should be disabled when complexity is not chosen.

**_Hints_**:
- we need to pass field size to the `Game` class
- select and button logic should not be in `Game` class but it can it

**Comment by liubich** [comment]
@probil, I have some questions:
1. separate screen with settings should appear at the game start or by some action on the main screen?
2. it shoult be modal or separate?
3. field size (5x7) gives 35 cards, this isn`t even number. I suggest (5x6)
4. timer should start on start button press?
5. can you help me with image source?

**Comment by probil** [comment]
> separate screen with settings should appear at the game start or by some action on the main screen?

At the game start. You can't start a game without selecting difficulty

> it shoult be modal or separate?

Doesn't matter

> field size (5x7) gives 35 cards, this isn`t even number. I suggest (5x6)

Good catch! Let it be `5x6`

> timer should start on start button press?

Yes

> can you help me with image source?

I will respond you later

**Comment by probil** [comment]
@liubich https://simpleicons.org/
