### ISSUE TITLE
CSS code quality tool (stylelint) integration

### ISSUE THREAD

**Issue by probil** [liubich/memory-game#21]
**Intro:** 
`stylelint` is the same as ESLint but for CSS (See #20).

Some things you can do with stylelint:
1) Catch errors
2) Enforce best practices
3) Enforce code style conventions
4) Customize and extend everything

**Tasks:**
- Install stylelint to your project (`devDependencies`)
- Add stylelint configuration, I suggest you to use [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard) but you can use any other rule set (or your own)
- Add npm task to run styleling using command through `npm run lint:css`
- Install [styleling plugin for VSCode](https://github.com/shinnn/vscode-stylelint)
- Run styleling on your codebase and fix all errors and warnings (as separate PR)

**Links:**
- https://css-tricks.com/stylelint/
- https://stylelint.io/
- https://github.com/stylelint/stylelint-config-standard
- https://www.smashingmagazine.com/2016/05/stylelint-the-style-sheet-linter-weve-always-wanted/

**Comment by liubich** [comment]
@probil, Is there a reason to add a stylelint check into CI job?

**Comment by probil** [comment]
@liubich Yes. Please add style check step to CI as well
