### ISSUE TITLE
Refactor with DDD approach

### ISSUE THREAD

**Issue by probil** [liubich/memory-game#27]
According to Data Driven Development your data/state should control how everything is rendered (including clicks, etc). It's easier to reason about as everything is controlled by flag somewhere. Your state is single source of truth. That's how modern FE frameworks work.

Currently you use simple data structure to describe cards like so:
```js
[1,4,1,3,5,4,...]; // <-- unique id of image to guess
```
Consider how you code and logic will change if your data structure will become something like this:
```js
const cards =  [
  {
    id: 1, // <-- unique id of the card
    hiddenValue: 3,  // <-- the id of image you try to guess
    isGuessed:  false,
    isOpened: false
  }, 
  {
    id: 2,
    hiddenValue: 2,
    isGuessed:  true, // <-- this card is hidden, ignores clicks etc
    isOpened: false
  },
  {
    id: 3,
    hiddenValue: 2,
    isGuessed:  true,
    isOpened: false
  },
  {
    id: 4,
    hiddenValue: 2,
    isGuessed:  false,
    isOpened: true, // <-- user just clicked on this card
  }, 
];
```
So it's much easier for `DOM_Manager` and `Game` to perform checks.
For example:
```js
// you don't have to update `nowOpened` all the time as it can be computed when needed (e.g. getter)
const nowOpened = cards.filter(card => card.isOpened).length;
```

- https://refactoring.guru/uk/smells/primitive-obsession

**Comment by liubich** [comment]
@probil, I have refactored the code in just another way (adding Card class). Can I close this issue?

**Comment by probil** [comment]
@liubich Card class is not what I mean. I'm sure you will do it while creating React versions of the game. So basically ye
